
String APIKEY="ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnVZVzFsSWpvaWFXNXBkR2xoYkNJc0ltTnNZWE56SWpvaVRXVnlZMmhoYm5RaUxDSndjbTltYVd4bFgzQnJJam8xTXpNNE1UVjkuTWZUdlF0WC1idlIwbjdyX2lwQnQ3S2tFYnAtdlJHTzc0NXJRcTZITDJ4QklaTlZPSG9weGJpRjNXR3d5Um0zejBtb0pOYVh6TlU2VzJzbGUwQm5oLWc=";

String PAYMENT_FIRST_TOKEN='';
String PAYMENT_ORDER_ID='';

String PAYMENT_FINAL_TOKEN_VISA='';
String PAYMENT_FINAL_TOKEN_KIOSK='';

String REFCODE='';

String INTGRATION_ID_VISACARD='2844106';
String INTGRATION_ID_KIOSK='2844127';

String FRAME_URL = 'https://accept.paymob.com/api/acceptance/iframes/680789?payment_token=';